### ISSUE TITLE
source file missing

### ISSUE THREAD

**Issue by rmcdermo** [BYUignite/sootlib#1]
@BYUignite Hi David,

When I tried to CMake the code (CMake 3.26.0), I get an error:
```
CMake Error at src/CMakeLists.txt:5 (add_library):
  Cannot find source file:

    /home4/rmcdermo/GitHub/sootlib_rmcdermo/sootlib/src/oxidationModels/oxidationModel_OPTJ.cc
```

**Comment by BYUignite** [comment]
Hi Randy.

I just added this file yesterday. I forgot to add the file when doing the git commit. It should be there now.

Would it be okay if I send in my review of the Fire Safety Science paper next week? I’m working on a talk on sootlib for the US combustion meeting on Monday and am a little behind on other things.

David O. Lignell
Professor, Chemical Engineering
Brigham Young University
801-422-1772 | http://ignite.byu.edu

On Mar 16, 2023, at 11:48 AM, Randy McDermott ***@***.******@***.***>> wrote:



@BYUignite<https://github.com/BYUignite> Hi David,

When I tried to CMake the code (CMake 3.26.0), I get an error:

CMake Error at src/CMakeLists.txt:5 (add_library):
  Cannot find source file:

    /home4/rmcdermo/GitHub/sootlib_rmcdermo/sootlib/src/oxidationModels/oxidationModel_OPTJ.cc<http://oxidationmodel_optj.cc>

**Comment by rmcdermo** [comment]
Hey David,
Thanks, it works!  I'll close the issue.

On the review, please see if you can give a quick review by tomorrow, as we are trying to stay on a very tight schedule for rebuttals.  Remember, the main thing is to think in terms of should this paper be accepted to the conference or not.  There will be another round of review for the actual journal article if it gets accepted to the conference.  Thanks!
