### ISSUE TITLE
Overflow of `p` and `q` in function `sootModel_MOMIC::set_fractional_moments_Mp6_Mq6`

### ISSUE THREAD

**Issue by TimoLin** [BYUignite/sootlib#3]
## Bug description
Hi, 
We're combining `sootlib` with `OpenFOAM` solver to model the soot formation in gaseous and spray flames.
In the following code:
https://github.com/BYUignite/sootlib/blob/b2e537e5f07b06a3306564af5140d43e22e1cfbe/src/sootModel_MOMIC.cc#L675-L685

The variable `p` and `q` are re-defined in the for loop using `size_t`. However `size_t` is used to define unsigned integers, **not negative values**.

This makes `p` and `q` are overflow in the first two iterations. For example, in my machine, output p in the loop gives the following values instead of `-4, -2, 0, 2, etc`:
```sh
18446744073709551612
18446744073709551614
0
2
...
```
## To fix the overflow:
```cpp
    double p = -4;
    for(size_t i=0; i<np[Nmom]; i++, p+=2)
        Mp6[i] = Mr(p/6.0);

    double q = -3;
    for(size_t i=0; i<nq[Nmom]; i++, q+=2)
        Mq6[i] = Mr(q/6.0);
```
## My environment:
- `Ubuntu 24.04`
- `g++-11`
- `cmake 3.25.2`
- `sootlib` latest commit b2e537e5f07b06a3306564af5140d43e22e1cfbe

This issued is reported by my colleague @jinyating233

**Comment by grabtheNS** [comment]
Yes,this bug does exist.  I reported this error to the author in early October, and I was also using OpenFOAM coupling. Perhaps we can exchange ideas and  discuss it together.

**Comment by jansenpb** [comment]
I apologize for the late reply, but I've updated the code to fix the issue. Thank you for bringing it to our attention.
